// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgFcxBLuk56X2yWUOJ8fQjR5nvXFDlZ4',
    appId: '1:791588998878:web:11468867eab7f646e83c4f',
    messagingSenderId: '791588998878',
    projectId: 'livaing-3ba94',
    authDomain: 'livaing-3ba94.firebaseapp.com',
    storageBucket: 'livaing-3ba94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChgRdqel-zAhYfe2e5-wIr62WAPZs3ios',
    appId: '1:791588998878:android:456f53b1c16525fce83c4f',
    messagingSenderId: '791588998878',
    projectId: 'livaing-3ba94',
    storageBucket: 'livaing-3ba94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTkEDmg9hLbk-1dpXLcnJwwTq4awAjwk',
    appId: '1:791588998878:ios:62f9d40d47b3dbbae83c4f',
    messagingSenderId: '791588998878',
    projectId: 'livaing-3ba94',
    storageBucket: 'livaing-3ba94.firebasestorage.app',
    iosBundleId: 'com.example.easyLivaign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTkEDmg9hLbk-1dpXLcnJwwTq4awAjwk',
    appId: '1:791588998878:ios:62f9d40d47b3dbbae83c4f',
    messagingSenderId: '791588998878',
    projectId: 'livaing-3ba94',
    storageBucket: 'livaing-3ba94.firebasestorage.app',
    iosBundleId: 'com.example.easyLivaign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEgFcxBLuk56X2yWUOJ8fQjR5nvXFDlZ4',
    appId: '1:791588998878:web:f87a60f90d290fcae83c4f',
    messagingSenderId: '791588998878',
    projectId: 'livaing-3ba94',
    authDomain: 'livaing-3ba94.firebaseapp.com',
    storageBucket: 'livaing-3ba94.firebasestorage.app',
  );
}
